
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('TiposLog').del()
    .then(function () {
      // Inserts seed entries
      return knex('TiposLog').insert([
        { Codigo: 'A',Descrição:'Área'},
        { Codigo: 'AC',Descrição:'Acesso'},
        { Codigo: 'ACA',Descrição:'Acampamento'},
        { Codigo:'ACL',Descrição:'Acesso Local'},
        { Codigo:'AD', Descrição:'Adro'},
        { Codigo:'AE', Descrição:'Área Especial'},
        { Codigo:'AER',Descrição:'Aeroporto'},
        { Codigo:'AL', Descrição:'Alameda'},
        { Codigo:'AMD',Descrição:'Avenida Marginal Direita'},
        { Codigo:'AME',Descrição:'Avenida Marginal Esquerda'},
        { Codigo:'AN', Descrição:'Anel Viário'},
        { Codigo:'ANT',Descrição:'Antiga Estrada'},
        { Codigo:'ART',Descrição:'Artéria'},
        { Codigo:'AT', Descrição:'Alto'},
        { Codigo:'ATL',Descrição:'Atalho'},
        { Codigo:'A V',Descrição:'Área Verde'},
        { Codigo:'AV', Descrição:'Avenida'},
        { Codigo:'AVC',Descrição:'Avenida Contorno'},
        { Codigo:'AVM',Descrição:'Avenida Marginal'},
        { Codigo:'AVV',Descrição:'Avenida Velha'},
        { Codigo:'BAL',Descrição:'Balneário'},
        { Codigo:'BC',Descrição:'Beco'},
        { Codigo:'BCO',Descrição:'Buraco'},
        { Codigo:'BEL',Descrição:'Belvedere'},
        { Codigo:'BL', Descrição:'Bloco'},
        { Codigo:'BLO',Descrição:'Balão'},
        { Codigo:'BLS',Descrição:'Blocos'},
        { Codigo:'BLV',Descrição:'Bulevar'},
        { Codigo:'BSQ',Descrição:'Bosque'},
        { Codigo:'BVD',Descrição:'Boulevard'},
        { Codigo:'BX', Descrição:'Baixa'},
        { Codigo:'C',  Descrição:'Cais'},
        { Codigo:'CAL',Descrição:'Calçada'},
        { Codigo:'CAM',Descrição:'Caminho'},
        { Codigo:'CAN',Descrição:'Canal'},
        { Codigo:'CH', Descrição:'Chácara'},
        { Codigo:'CHA',Descrição:'Chapadão'},
        { Codigo:'CIC',Descrição:'Ciclovia'},
        { Codigo:'CIR',Descrição:'Circular'},
        { Codigo:'CJ', Descrição:'Conjunto'},
        { Codigo:'CJM',Descrição:'Conjunto Mutirão'},
        { Codigo:'CMP',Descrição:'Complexo Viário'},
        { Codigo:'COL',Descrição:'Colônia'},
        { Codigo:'COM',Descrição:'Comunidade'},
        { Codigo:'CON',Descrição:'Condomínio'},
        { Codigo:'COR',Descrição:'Corredor'},
        { Codigo:'CPO',Descrição:'Campo'},
        { Codigo:'CRG',Descrição:'Córrego'},
        { Codigo:'CTN',Descrição:'Contorno'},
        { Codigo:'DSC',Descrição:'Descida'},
        { Codigo:'DSV',Descrição:'Desvio'},
        { Codigo:'DT', Descrição:'Distrito'},
        { Codigo:'EB', Descrição:'Entre Bloco'},
        { Codigo:'EIM',Descrição:'Estrada Intermunicipal'},
        { Codigo:'ENS',Descrição:'Enseada'},
        { Codigo:'ENT',Descrição:'Entrada Particular'},
        { Codigo:'EQ', Descrição:'Entre Quadra'},
        { Codigo:'ESC',Descrição:'Escada'},
        { Codigo:'ESD',Descrição:'Escadaria'},
        { Codigo:'ESE',Descrição:'Estrada Estadual'},
        { Codigo:'ESI',Descrição:'Estrada Vicinal'},
        { Codigo:'ESL',Descrição:'Estrada de Ligação'},
        { Codigo:'ESM',Descrição:'Estrada Municipal'},
        { Codigo:'ESP',Descrição:'Esplanada'},
        { Codigo:'ESS',Descrição:'Estrada de Servidão'},
        { Codigo:'EST',Descrição:'Estrada'},
        { Codigo:'ESV',Descrição:'Estrada Velha'},
        { Codigo:'ETA',Descrição:'Estrada Antiga'},
        { Codigo:'ETC',Descrição:'Estação'},
        { Codigo:'ETD',Descrição:'Estádio'},
        { Codigo:'ETN',Descrição:'Estância'},
        { Codigo:'ETP',Descrição:'Estrada Particular'},
        { Codigo:'ETT',Descrição:'Estacionamento'},
        { Codigo:'EVA',Descrição:'Evangélica'},
        { Codigo:'EVD',Descrição:'Elevada'},
        { Codigo:'EX', Descrição:'Eixo Industrial'},
        { Codigo:'FAV',Descrição:'Favela'},
        { Codigo:'FAZ',Descrição:'Fazenda'},
        { Codigo:'FER',Descrição:'Ferrovia'},
        { Codigo:'FNT',Descrição:'Fonte'},
        { Codigo:'FRA',Descrição:'Feira'},
        { Codigo:'FTE',Descrição:'Forte'},
        { Codigo:'GAL',Descrição:'Galeria'},
        { Codigo:'GJA',Descrição:'Granja'},
        { Codigo:'HAB',Descrição:'Núcleo Habitacional'},
        { Codigo:'IA', Descrição:'Ilha'},
        { Codigo:'IND',Descrição:'Indeterminado'},
        { Codigo:'IOA',Descrição:'Ilhota'},
        { Codigo:'JD', Descrição:'Jardim'},
        { Codigo:'JDE',Descrição:'Jardinete'},
        { Codigo:'LD', Descrição:'Ladeira'},
        { Codigo:'LGA',Descrição:'Lagoa'},
        { Codigo:'LGO',Descrição:'Lago'},
        { Codigo:'LOT',Descrição:'Loteamento'},
        { Codigo:'LRG',Descrição:'Largo'},
        { Codigo:'LT', Descrição:'Lote'},
        { Codigo:'MER',Descrição:'Mercado'},
        { Codigo:'MNA',Descrição:'Marina'},
        { Codigo:'MOD',Descrição:'Modulo'},
        { Codigo:'MRG',Descrição:'Projeção'},
        { Codigo:'MRO',Descrição:'Morro'},
        { Codigo:'MTE',Descrição:'Monte'},
        { Codigo:'NUC',Descrição:'Núcleo'},
        { Codigo:'NUR',Descrição:'Núcleo Rural'},
        { Codigo:'OUT',Descrição:'Outeiro'},
        { Codigo:'PAR',Descrição:'Paralela'},
        { Codigo:'PAS',Descrição:'Passeio'},
        { Codigo:'PAT',Descrição:'Pátio'},
        { Codigo:'PC', Descrição:'Praça'},
        { Codigo:'PCE',Descrição:'Praça de Esportes'},
        { Codigo:'PDA',Descrição:'Parada'},
        { Codigo:'PDO',Descrição:'Paradouro'},
        { Codigo:'PNT',Descrição:'Ponta'},
        { Codigo:'PR', Descrição:'Praia'},
        { Codigo:'PRL',Descrição:'Prolongamento'},
        { Codigo:'PRM',Descrição:'Parque Municipal'},
        { Codigo:'PRQ',Descrição:'Parque'},
        { Codigo:'PRR',Descrição:'Parque Residencial'},
        { Codigo:'PSA',Descrição:'Passarela'},
        { Codigo:'PSG',Descrição:'Passagem'},
        { Codigo:'PSP',Descrição:'Passagem de Pedestre'},
        { Codigo:'PSS',Descrição:'Passagem Subterrânea'},
        { Codigo:'PTE',Descrição:'Ponte'},
        { Codigo:'PTO',Descrição:'Porto'},
        { Codigo:'Q',  Descrição:'Quadra'},
        { Codigo:'QTA',Descrição:'Quinta'},
        { Codigo:'QTS',Descrição:'Quintas'},
        { Codigo:'R',  Descrição:'Rua'},
        { Codigo:'R I',Descrição:'Rua Integração'},
        { Codigo:'R L',Descrição:'Rua de Ligação'},
        { Codigo:'R P',Descrição:'Rua Particular'},
        { Codigo:'R V',Descrição:'Rua Velha'},
        { Codigo:'RAM',Descrição:'Ramal'},
        { Codigo:'RCR',Descrição:'Recreio'},
        { Codigo:'REC',Descrição:'Recanto'},
        { Codigo:'RER',Descrição:'Retiro'},
        { Codigo:'RES',Descrição:'Residencial'},
        { Codigo:'RET',Descrição:'Reta'},
        { Codigo:'RLA',Descrição:'Ruela'},
        { Codigo:'RMP',Descrição:'Rampa'},
        { Codigo:'ROA',Descrição:'Rodo Anel'},
        { Codigo:'ROD',Descrição:'Rodovia'},
        { Codigo:'ROT',Descrição:'Rotula'},
        { Codigo:'RPE',Descrição:'Rua de Pedestre'},
        { Codigo:'RPR',Descrição:'Margem'},
        { Codigo:'RTN',Descrição:'Retorno'},
        { Codigo:'RTT',Descrição:'Rotatória'},
        { Codigo:'SEG',Descrição:'Segunda Avenida'},
        { Codigo:'SIT',Descrição:'Sitio'},
        { Codigo:'SRV',Descrição:'Servidão'},
        { Codigo:'ST', Descrição:'Setor'},
        { Codigo:'SUB',Descrição:'Subida'},
        { Codigo:'TCH',Descrição:'Trincheira'},
        { Codigo:'TER',Descrição:'Terminal'},
        { Codigo:'TR', Descrição:'Trecho'},
        { Codigo:'TRV',Descrição:'Trevo'},
        { Codigo:'TUN',Descrição:'Túnel'},
        { Codigo:'TV', Descrição:'Travessa'},
        { Codigo:'TVP',Descrição:'Travessa Particular'},
        { Codigo:'TVV',Descrição:'Travessa Velha'},
        { Codigo:'UNI',Descrição:'Unidade'},
        { Codigo:'V',  Descrição:'Via'},
        { Codigo:'V C',Descrição:'Via Coletora'},
        { Codigo:'V L',Descrição:'Via Local'},
        { Codigo:'VAC',Descrição:'Via de Acesso'},
        { Codigo:'VAL',Descrição:'Vala'},
        { Codigo:'VCO',Descrição:'Via Costeira'},
        { Codigo:'VD', Descrição:'Viaduto'},
        { Codigo:'V-E',Descrição:'Via Expressa'},
        { Codigo:'VER',Descrição:'Vereda'},
        { Codigo:'VEV',Descrição:'Via Elevado'},
        { Codigo:'VL', Descrição:'Vila'},
        { Codigo:'VLA',Descrição:'Viela'},
        { Codigo:'VLE',Descrição:'Vale'},
        { Codigo:'VLT',Descrição:'Via Litorânea'},
        { Codigo:'VPE',Descrição:'Via de Pedestre'},
        { Codigo:'VRT',Descrição:'Variante'},
        { Codigo:'ZIG',Descrição:'Zigue-Zague'},        
      ]);
    });
};
