
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('TypespPublicPlace').del()
    .then(function () {
      // Inserts seed entries
      return knex('TypespPublicPlace').insert([
        { Code: 'A',Descripition:'Área'},
        { Code: 'AC',Descripition:'Acesso'},
        { Code: 'ACA',Descripition:'Acampamento'},
        { Code:'ACL',Descripition:'Acesso Local'},
        { Code:'AD', Descripition:'Adro'},
        { Code:'AE', Descripition:'Área Especial'},
        { Code:'AER',Descripition:'Aeroporto'},
        { Code:'AL', Descripition:'Alameda'},
        { Code:'AMD',Descripition:'Avenida Marginal Direita'},
        { Code:'AME',Descripition:'Avenida Marginal Esquerda'},
        { Code:'AN', Descripition:'Anel Viário'},
        { Code:'ANT',Descripition:'Antiga Estrada'},
        { Code:'ART',Descripition:'Artéria'},
        { Code:'AT', Descripition:'Alto'},
        { Code:'ATL',Descripition:'Atalho'},
        { Code:'A V',Descripition:'Área Verde'},
        { Code:'AV', Descripition:'Avenida'},
        { Code:'AVC',Descripition:'Avenida Contorno'},
        { Code:'AVM',Descripition:'Avenida Marginal'},
        { Code:'AVV',Descripition:'Avenida Velha'},
        { Code:'BAL',Descripition:'Balneário'},
        { Code:'BC',Descripition:'Beco'},
        { Code:'BCO',Descripition:'Buraco'},
        { Code:'BEL',Descripition:'Belvedere'},
        { Code:'BL', Descripition:'Bloco'},
        { Code:'BLO',Descripition:'Balão'},
        { Code:'BLS',Descripition:'Blocos'},
        { Code:'BLV',Descripition:'Bulevar'},
        { Code:'BSQ',Descripition:'Bosque'},
        { Code:'BVD',Descripition:'Boulevard'},
        { Code:'BX', Descripition:'Baixa'},
        { Code:'C',  Descripition:'Cais'},
        { Code:'CAL',Descripition:'Calçada'},
        { Code:'CAM',Descripition:'Caminho'},
        { Code:'CAN',Descripition:'Canal'},
        { Code:'CH', Descripition:'Chácara'},
        { Code:'CHA',Descripition:'Chapadão'},
        { Code:'CIC',Descripition:'Ciclovia'},
        { Code:'CIR',Descripition:'Circular'},
        { Code:'CJ', Descripition:'Conjunto'},
        { Code:'CJM',Descripition:'Conjunto Mutirão'},
        { Code:'CMP',Descripition:'Complexo Viário'},
        { Code:'COL',Descripition:'Colônia'},
        { Code:'COM',Descripition:'Comunidade'},
        { Code:'CON',Descripition:'Condomínio'},
        { Code:'COR',Descripition:'Corredor'},
        { Code:'CPO',Descripition:'Campo'},
        { Code:'CRG',Descripition:'Córrego'},
        { Code:'CTN',Descripition:'Contorno'},
        { Code:'DSC',Descripition:'Descida'},
        { Code:'DSV',Descripition:'Desvio'},
        { Code:'DT', Descripition:'Distrito'},
        { Code:'EB', Descripition:'Entre Bloco'},
        { Code:'EIM',Descripition:'Estrada Intermunicipal'},
        { Code:'ENS',Descripition:'Enseada'},
        { Code:'ENT',Descripition:'Entrada Particular'},
        { Code:'EQ', Descripition:'Entre Quadra'},
        { Code:'ESC',Descripition:'Escada'},
        { Code:'ESD',Descripition:'Escadaria'},
        { Code:'ESE',Descripition:'Estrada Estadual'},
        { Code:'ESI',Descripition:'Estrada Vicinal'},
        { Code:'ESL',Descripition:'Estrada de Ligação'},
        { Code:'ESM',Descripition:'Estrada Municipal'},
        { Code:'ESP',Descripition:'Esplanada'},
        { Code:'ESS',Descripition:'Estrada de Servidão'},
        { Code:'EST',Descripition:'Estrada'},
        { Code:'ESV',Descripition:'Estrada Velha'},
        { Code:'ETA',Descripition:'Estrada Antiga'},
        { Code:'ETC',Descripition:'Estação'},
        { Code:'ETD',Descripition:'Estádio'},
        { Code:'ETN',Descripition:'Estância'},
        { Code:'ETP',Descripition:'Estrada Particular'},
        { Code:'ETT',Descripition:'Estacionamento'},
        { Code:'EVA',Descripition:'Evangélica'},
        { Code:'EVD',Descripition:'Elevada'},
        { Code:'EX', Descripition:'Eixo Industrial'},
        { Code:'FAV',Descripition:'Favela'},
        { Code:'FAZ',Descripition:'Fazenda'},
        { Code:'FER',Descripition:'Ferrovia'},
        { Code:'FNT',Descripition:'Fonte'},
        { Code:'FRA',Descripition:'Feira'},
        { Code:'FTE',Descripition:'Forte'},
        { Code:'GAL',Descripition:'Galeria'},
        { Code:'GJA',Descripition:'Granja'},
        { Code:'HAB',Descripition:'Núcleo Habitacional'},
        { Code:'IA', Descripition:'Ilha'},
        { Code:'IND',Descripition:'Indeterminado'},
        { Code:'IOA',Descripition:'Ilhota'},
        { Code:'JD', Descripition:'Jardim'},
        { Code:'JDE',Descripition:'Jardinete'},
        { Code:'LD', Descripition:'Ladeira'},
        { Code:'LGA',Descripition:'Lagoa'},
        { Code:'LGO',Descripition:'Lago'},
        { Code:'LOT',Descripition:'Loteamento'},
        { Code:'LRG',Descripition:'Largo'},
        { Code:'LT', Descripition:'Lote'},
        { Code:'MER',Descripition:'Mercado'},
        { Code:'MNA',Descripition:'Marina'},
        { Code:'MOD',Descripition:'Modulo'},
        { Code:'MRG',Descripition:'Projeção'},
        { Code:'MRO',Descripition:'Morro'},
        { Code:'MTE',Descripition:'Monte'},
        { Code:'NUC',Descripition:'Núcleo'},
        { Code:'NUR',Descripition:'Núcleo Rural'},
        { Code:'OUT',Descripition:'Outeiro'},
        { Code:'PAR',Descripition:'Paralela'},
        { Code:'PAS',Descripition:'Passeio'},
        { Code:'PAT',Descripition:'Pátio'},
        { Code:'PC', Descripition:'Praça'},
        { Code:'PCE',Descripition:'Praça de Esportes'},
        { Code:'PDA',Descripition:'Parada'},
        { Code:'PDO',Descripition:'Paradouro'},
        { Code:'PNT',Descripition:'Ponta'},
        { Code:'PR', Descripition:'Praia'},
        { Code:'PRL',Descripition:'Prolongamento'},
        { Code:'PRM',Descripition:'Parque Municipal'},
        { Code:'PRQ',Descripition:'Parque'},
        { Code:'PRR',Descripition:'Parque Residencial'},
        { Code:'PSA',Descripition:'Passarela'},
        { Code:'PSG',Descripition:'Passagem'},
        { Code:'PSP',Descripition:'Passagem de Pedestre'},
        { Code:'PSS',Descripition:'Passagem Subterrânea'},
        { Code:'PTE',Descripition:'Ponte'},
        { Code:'PTO',Descripition:'Porto'},
        { Code:'Q',  Descripition:'Quadra'},
        { Code:'QTA',Descripition:'Quinta'},
        { Code:'QTS',Descripition:'Quintas'},
        { Code:'R',  Descripition:'Rua'},
        { Code:'R I',Descripition:'Rua Integração'},
        { Code:'R L',Descripition:'Rua de Ligação'},
        { Code:'R P',Descripition:'Rua Particular'},
        { Code:'R V',Descripition:'Rua Velha'},
        { Code:'RAM',Descripition:'Ramal'},
        { Code:'RCR',Descripition:'Recreio'},
        { Code:'REC',Descripition:'Recanto'},
        { Code:'RER',Descripition:'Retiro'},
        { Code:'RES',Descripition:'Residencial'},
        { Code:'RET',Descripition:'Reta'},
        { Code:'RLA',Descripition:'Ruela'},
        { Code:'RMP',Descripition:'Rampa'},
        { Code:'ROA',Descripition:'Rodo Anel'},
        { Code:'ROD',Descripition:'Rodovia'},
        { Code:'ROT',Descripition:'Rotula'},
        { Code:'RPE',Descripition:'Rua de Pedestre'},
        { Code:'RPR',Descripition:'Margem'},
        { Code:'RTN',Descripition:'Retorno'},
        { Code:'RTT',Descripition:'Rotatória'},
        { Code:'SEG',Descripition:'Segunda Avenida'},
        { Code:'SIT',Descripition:'Sitio'},
        { Code:'SRV',Descripition:'Servidão'},
        { Code:'ST', Descripition:'Setor'},
        { Code:'SUB',Descripition:'Subida'},
        { Code:'TCH',Descripition:'Trincheira'},
        { Code:'TER',Descripition:'Terminal'},
        { Code:'TR', Descripition:'Trecho'},
        { Code:'TRV',Descripition:'Trevo'},
        { Code:'TUN',Descripition:'Túnel'},
        { Code:'TV', Descripition:'Travessa'},
        { Code:'TVP',Descripition:'Travessa Particular'},
        { Code:'TVV',Descripition:'Travessa Velha'},
        { Code:'UNI',Descripition:'Unidade'},
        { Code:'V',  Descripition:'Via'},
        { Code:'V C',Descripition:'Via Coletora'},
        { Code:'V L',Descripition:'Via Local'},
        { Code:'VAC',Descripition:'Via de Acesso'},
        { Code:'VAL',Descripition:'Vala'},
        { Code:'VCO',Descripition:'Via Costeira'},
        { Code:'VD', Descripition:'Viaduto'},
        { Code:'V-E',Descripition:'Via Expressa'},
        { Code:'VER',Descripition:'Vereda'},
        { Code:'VEV',Descripition:'Via Elevado'},
        { Code:'VL', Descripition:'Vila'},
        { Code:'VLA',Descripition:'Viela'},
        { Code:'VLE',Descripition:'Vale'},
        { Code:'VLT',Descripition:'Via Litorânea'},
        { Code:'VPE',Descripition:'Via de Pedestre'},
        { Code:'VRT',Descripition:'Variante'},
        { Code:'ZIG',Descripition:'Zigue-Zague'},        
      ]);
    });
};
